apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: tech-challenge2
type: Opaque
#data:
#POSTGRES_USERNAME: <BASE64_POSTGRES_USERNAME>
#POSTGRES_PASSWORD: <BASE64_POSTGRES_PASSWORD>

#REDIS_PASSWORD: <BASE64_REDIS_PASSWORD>
  
#AWS_ACCESS_KEY_ID: <BASE64_AWS_ACCESS_KEY_ID>
#AWS_SECRET_ACCESS_KEY: <BASE64_AWS_SECRET_ACCESS_KEY>
stringData:
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: postgres123
  REDIS_PASSWORD: redis132
  AWS_ACCESS_KEY_ID: test-access-key
  AWS_SECRET_ACCESS_KEY: test-secret-key