apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secret
  namespace: tech-challenge2
type: Opaque
data:
  SERVICE_API_KEY: <Preencher>
  AWS_ACCESS_KEY_ID: <Preencher>
  AWS_SECRET_ACCESS_KEY: <Preencher>
#echo -n 'Colocar key - IAM' | base64