apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-config
  namespace: tech-challenge2

data:
  PORT: "8004"
  REDIS_URL: "<Colocar ElastiCache AWS>"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
  AWS_REGION: "<Colocar regiao AWS>"
  AWS_SQS_URL: "<url qos AWS>"